import type { Class, SystemMetrics, AdminReport, BulkEmail, User } from '@/lib/pcdc-types';
import { UserRole } from '@/lib/pcdc-types';

export const adminUsers: User[] = [
  { id: 'user1', name: 'Alice Johnson', email: 'alice@example.com', role: UserRole.STUDENT },
  { id: 'user2', name: 'Bob Smith', email: 'bob@example.com', role: UserRole.STUDENT },
  { id: 'user3', name: 'Carol White', email: 'carol@example.com', role: UserRole.STUDENT },
  { id: 'user4', name: 'David Brown', email: 'david@example.com', role: UserRole.STUDENT },
  { id: 'user5', name: 'Emma Davis', email: 'emma@example.com', role: UserRole.STUDENT },
  { id: 'teacher1', name: 'Mr. Anderson', email: 'anderson@example.com', role: UserRole.TEACHER },
  { id: 'teacher2', name: 'Ms. Taylor', email: 'taylor@example.com', role: UserRole.TEACHER },
  { id: 'teacher3', name: 'Mrs. Martinez', email: 'martinez@example.com', role: UserRole.TEACHER },
  { id: 'parent1', name: 'Sarah Johnson', email: 'sarah.j@example.com', role: UserRole.PARENT, studentIds: ['user1'] },
  { id: 'parent2', name: 'Michael Smith', email: 'michael.s@example.com', role: UserRole.PARENT, studentIds: ['user2'] },
  { id: 'parent3', name: 'Lisa Brown', email: 'lisa.b@example.com', role: UserRole.PARENT, studentIds: ['user3', 'user4'] },
  { id: 'admin1', name: 'Admin User', email: 'admin@pcdc.ai', role: UserRole.ADMIN },
];

export const adminClasses: Class[] = [
  {
    id: 'class1',
    name: 'Algebra Fundamentals',
    subject: 'Mathematics',
    grade: 'Grade 8',
    teacherId: 'teacher1',
    teacherName: 'Mr. Anderson',
    maxCapacity: 25,
    enrolledStudents: ['user1', 'user2', 'user3'],
    waitlist: ['user4'],
    schedule: 'Mon/Wed/Fri 3:00 PM',
    status: 'active',
    startDate: new Date('2026-01-15'),
    endDate: new Date('2026-06-30'),
  },
  {
    id: 'class2',
    name: 'Advanced Geometry',
    subject: 'Mathematics',
    grade: 'Grade 10',
    teacherId: 'teacher2',
    teacherName: 'Ms. Taylor',
    maxCapacity: 20,
    enrolledStudents: ['user5'],
    waitlist: [],
    schedule: 'Tue/Thu 4:00 PM',
    status: 'active',
    startDate: new Date('2026-02-01'),
    endDate: new Date('2026-07-31'),
  },
  {
    id: 'class3',
    name: 'Pre-Calculus Prep',
    subject: 'Mathematics',
    grade: 'Grade 11',
    teacherId: 'teacher3',
    teacherName: 'Mrs. Martinez',
    maxCapacity: 15,
    enrolledStudents: [],
    waitlist: [],
    schedule: 'Mon/Wed 5:30 PM',
    status: 'upcoming',
    startDate: new Date('2026-06-01'),
    endDate: new Date('2026-12-31'),
  },
  {
    id: 'class4',
    name: 'Basic Math Skills',
    subject: 'Mathematics',
    grade: 'Grade 7',
    teacherId: 'teacher1',
    teacherName: 'Mr. Anderson',
    maxCapacity: 30,
    enrolledStudents: ['user1', 'user2', 'user3', 'user4', 'user5'],
    waitlist: [],
    schedule: 'Tue/Thu/Sat 2:00 PM',
    status: 'active',
    startDate: new Date('2026-01-10'),
    endDate: new Date('2026-06-30'),
  },
];

export const systemMetrics: SystemMetrics = {
  totalUsers: 287,
  activeStudents: 198,
  activeTeachers: 24,
  totalClasses: 18,
  totalAssessments: 1456,
  averageMasteryScore: 76.4,
  platformUptime: 99.97,
  apiResponseTime: 145,
  storageUsed: '12.4 GB',
  lastBackup: new Date('2026-05-04T02:00:00Z'),
};

export const adminReports: AdminReport[] = [
  {
    id: 'report1',
    title: 'Monthly Student Performance Report - April 2026',
    type: 'student_performance',
    generatedAt: new Date('2026-05-01T10:00:00Z'),
    generatedBy: 'admin1',
    data: { totalStudents: 198, averageScore: 76.4, improvementRate: 12.3 },
    format: 'pdf',
  },
  {
    id: 'report2',
    title: 'Class Analytics Q1 2026',
    type: 'class_analytics',
    generatedAt: new Date('2026-04-15T14:30:00Z'),
    generatedBy: 'admin1',
    data: { totalClasses: 18, averageAttendance: 87.2, completionRate: 82.5 },
    format: 'pdf',
  },
  {
    id: 'report3',
    title: 'Platform Usage Statistics - April',
    type: 'system_usage',
    generatedAt: new Date('2026-05-02T09:00:00Z'),
    generatedBy: 'admin1',
    data: { activeUsers: 222, totalSessions: 3456, averageSessionDuration: 28 },
    format: 'csv',
  },
  {
    id: 'report4',
    title: 'Student Attendance Report - Week 18',
    type: 'attendance',
    generatedAt: new Date('2026-05-03T16:00:00Z'),
    generatedBy: 'admin1',
    data: { present: 176, absent: 22, attendanceRate: 88.9 },
    format: 'excel',
  },
];

export const bulkEmails: BulkEmail[] = [
  {
    id: 'email1',
    subject: 'Important: Platform Maintenance Schedule',
    body: 'Dear users, we will be performing scheduled maintenance on...',
    recipientType: 'all_students',
    recipientCount: 198,
    sentAt: new Date('2026-05-01T08:00:00Z'),
    sentBy: 'admin1',
    status: 'sent',
  },
  {
    id: 'email2',
    subject: 'Congratulations on Your Progress!',
    body: 'We noticed significant improvement in your recent assessments...',
    recipientType: 'at_risk_students',
    recipientCount: 15,
    sentAt: new Date('2026-04-28T10:00:00Z'),
    sentBy: 'admin1',
    status: 'sent',
  },
  {
    id: 'email3',
    subject: 'Teacher Training Session - May 15',
    body: 'All teachers are invited to attend a professional development session...',
    recipientType: 'all_teachers',
    recipientCount: 24,
    sentAt: new Date('2026-04-25T12:00:00Z'),
    sentBy: 'admin1',
    status: 'sent',
  },
  {
    id: 'email4',
    subject: 'Weekly Progress Update',
    body: 'Here is your child\'s learning progress for this week...',
    recipientType: 'all_parents',
    recipientCount: 142,
    sentAt: new Date('2026-05-04T09:00:00Z'),
    sentBy: 'admin1',
    status: 'scheduled',
  },
];
